### ISSUE TITLE
Cannot execute CLS properly

### ISSUE THREAD

**Issue by samitainio** [jeremejevs/cmdcolor#10]
I'm calling for a .bat file with:

script.bat | cmdcolor.exe

script.bat has the following lines:

@echo off
echo This line should clear out.
cls
echo This line should be only visible.
pause

Executing the script leads to the following:
![screensnip](https://cloud.githubusercontent.com/assets/5585477/9747549/e1ac1674-5686-11e5-8b4b-db8fa4106f1e.PNG)

Any ideas how to fix this and get CLS to clear the screen normally?

**Comment by jeremejevs** [comment]
I'm afraid this isn't possible to fix, at least not without any hacks on user's side. The problem is, when redirected (as in case with `cmdcolor`), [`CLS` simply outputs an LF](http://ss64.com/nt/cls.html), which isn't distinguishable from the regular LF.

One way around this would be to treat any LF without a preceding CR as a `clear screen`, but that's just asking for trouble, since there are legitimate use cases for LF.

Another way would be to print some special character or a combination of them on the user's side, denoting a `clear screen`, instead of calling `CLS`, but then might as well just do something like this:

```batch
@echo off
echo This line should clear out. | cmdcolor.exe
cls
echo This line should be only visible. | cmdcolor.exe
pause
```

And avoid any "magic" altogether (which can also be broken quite easily).

Sorry for not having a solution for you. Please, let me know if you think there's a third way.

**Comment by kcris** [comment]
add some arg to cmdcolor?

--enable-cls ?

or

--ignore-lf ?

**Comment by alecmev** [comment]
@kcris I assume this isn't needed anymore, as Windows 10 has this built in?
